version: "3.8"
services:

  fr-app:
    depends_on:
      - fr-postgres
    image: "docker.io/sonnykrieg/franchise-app"
    container_name: "fr-app"
    ports:
      - 8080:8080

    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - SPRING_R2DBC_URL=r2dbc:postgresql://fr-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://fr-postgres:5432/polardb_order

  fr-postgres:
    image: "postgres:14.12"
    container_name: "fr-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_order
